/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnidemo_NativeImplementation */

#ifndef _Included_jnidemo_NativeImplementation
#define _Included_jnidemo_NativeImplementation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnidemo_NativeImplementation
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jnidemo_NativeImplementation_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jnidemo_NativeImplementation
 * Method:    multiply
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jnidemo_NativeImplementation_multiply
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
